name: Build and Test PR

on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop

defaults:
  run:
    shell: bash

jobs:

  lint:
    name: 'Run linter'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.15.0'

      - name: Install dependencies
        run: npm ci

      - run: npm run lint

  build:
    runs-on: ubuntu-latest
    needs: [ lint]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.15.0'

      - name: Install dependencies
        run: npm ci

      - name: Build main.bundle.js
        run: npm run build:qa
      - run: npm run cp:all

