name: Build and Test PR

on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.15.0'

      - name: Install dependencies
        run: npm ci

      - name: "Set current datetime as env variable"
        run: |
          echo "builddate=$(date +'%Y-%m-%dT%H:%M:%S%z')" >> $GITHUB_OUTPUT
        id: version  # this is used on variable path

      - name: "Get short SHA of the commit"
        uses: bhowell2/github-substring-action@1.0.2
        id: shortSHA
        with:
          value: ${{ github.event.head_commit.id }}
          length_from_start: 7

      - name: Build main.bundle.js
        run: npm run build:qa -- --env=version=${{ steps.shortSHA.outputs.substring }} --env=lastChange=${{ steps.version.outputs.builddate }}
      - run: npm run cp:all

      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: qa-artifacts
          path: ./public
