name: Build and Test PR

on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.15.0'

      - name: Install dependencies
        run: npm ci

      - name: Build main.bundle.js
        run: npm run build:qa
      - run: npm run cp:all

      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: qa-artifacts
          path: ./public
