name: Deploy to PROD

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.15.0'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: "Set current datetime as env variable"
        run: |
          echo "builddate=$(date +'%Y-%m-%dT%H:%M:%S%z')" >> $GITHUB_OUTPUT
        id: version  # this is used on variable path

      - name: Build main.bundle.js
        run: npm run build:qa -- --env=lastChange=${{ steps.version.outputs.builddate }}
      - run: npm run cp:all

      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: qa-artifacts
          path: ./public

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4.1.7
        with:
          name: qa-artifacts
          path: ./public

      - name: Upload to QA using Web FTP
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.QA_SERVER }}
          username: ${{ secrets.QA_FTP_USER }}
          password: ${{ secrets.QA_FTP_PASS }}
          local-dir: './public/'
          server-dir: '/'
          protocol: 'ftps'
