name: Deploy to QA

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.15.0'

      - name: Install dependencies
        run: npm ci

      - name: Build main.bundle.js
        run: npm run build:qa

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Upload to QA using Web FTP
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.QA_SERVER }}
          username: ${{ secrets.QA_FTP_USER }}
          password: ${{ secrets.QA_FTP_PASS }}
          local-dir: './public/'
          server-dir: '/'
